import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { logout } from "@/app/actions";
import { getWorkspace } from "@/lib/auth/workspace";
import { getLocalActor } from "@/lib/local/session";
import { getDb } from "@/lib/local/db";
import { listAgents, listMacros, listSlaPolicies, listTags } from "@/lib/local/tickets";
import { createMacroAction, createTagAction, updateSlaAction, updateWorkspaceAction } from "@/features/settings/actions";

export const metadata: Metadata = { title: "Configurações" };
export const dynamic = "force-dynamic";
const sections = ["workspace", "members", "sla", "tags", "macros", "security", "privacy", "audit"] as const;

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ section?: string }> }) {
  const actor = await getLocalActor();
  if (actor.role !== "owner" && actor.role !== "admin") redirect("/app");
  const workspace = await getWorkspace();
  const params = await searchParams;
  const section = sections.find((item) => item === params.section) ?? "workspace";
  const agents = listAgents(actor);
  const policies = listSlaPolicies(actor);
  const tags = listTags(actor);
  const macros = listMacros(actor);
  const privacyRequests = getDb().prepare("select p.id,p.request_kind,p.status,p.created_at,a.name,a.email from privacy_requests p join accounts a on a.id=p.account_id where a.organization_id=? order by p.created_at desc limit 50").all(actor.organizationId) as { id: string; request_kind: string; status: string; created_at: string; name: string; email: string }[];
  const audit = getDb().prepare("select * from audit_logs where organization_id=? order by created_at desc limit 30").all(actor.organizationId) as { id: string; actor_id: string; entity_type: string; action: string; old_value: string | null; new_value: string | null; created_at: string }[];
  return <><div className="page-heading"><div><div className="eyebrow">WORKSPACE</div><h1>Configurações</h1><p className="muted">Políticas, respostas rápidas e transparência operacional.</p></div></div><div className="settings-layout"><nav className="settings-nav" aria-label="Seções de configuração">{sections.map((item) => <Link key={item} href={`/app/settings?section=${item}`} className={section === item ? "active" : ""}>{({ workspace: "Workspace", members: "Membros", sla: "SLA", tags: "Tags", macros: "Respostas rápidas", security: "Segurança", privacy: "Privacidade", audit: "Auditoria" } as Record<string,string>)[item]}</Link>)}</nav><div className="settings-content">
    {section === "workspace" && <section className="panel form-panel"><div className="eyebrow">ORGANIZAÇÃO</div><h2>Dados do workspace</h2><p className="muted">As mudanças de nome aparecem imediatamente na navegação.</p><form action={updateWorkspaceAction}><label className="form-field">Nome<input className="text-input" name="name" defaultValue={workspace.name} minLength={2} maxLength={80} required/></label><button className="button-primary" type="submit">Salvar nome</button></form><div className="property-divider"/><div className="property-meta">Código para cadastro de clientes: <strong>{workspace.slug}</strong></div><div className="property-meta">Backend atual: {process.env.DATABASE_URL ? "PostgreSQL local" : "SQLite local"}</div></section>}
    {section === "members" && <section className="panel"><div className="section-head"><h2>Membros da equipe</h2><span className="muted">{agents.length} pessoas</span></div>{agents.map((agent) => <div className="team-row" key={agent.id}><span className="avatar">{agent.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div><strong>{agent.name}</strong><small>{agent.email}</small></div><span className="plain-pill">{agent.role}</span></div>)}<div className="notice" style={{ margin: 18 }}>Papéis e estados são administrados no terminal com <code>npm run account:set</code>.</div></section>}
    {section === "sla" && <section className="panel"><div className="section-head"><h2>Políticas de SLA</h2></div><div style={{ padding: 20 }}><p className="muted">Prazos em minutos corridos usados para primeira resposta e resolução no modo local.</p>{policies.map((policy) => <form action={updateSlaAction} className="sla-policy-row" key={policy.id}><input type="hidden" name="id" value={policy.id}/><strong>{policy.name}</strong><label>Primeira resposta<input className="text-input" name="first" type="number" min={1} max={10080} defaultValue={policy.first_response_minutes} required/></label><label>Resolução<input className="text-input" name="resolution" type="number" min={1} max={43200} defaultValue={policy.resolution_minutes} required/></label><button type="submit" className="button-secondary">Salvar</button></form>)}</div></section>}
    {section === "tags" && <section className="panel form-panel"><h2>Tags</h2><div className="tag-cloud">{tags.map((tag) => <span className="plain-pill" key={tag}>{tag}</span>)}</div><form action={createTagAction} className="inline-form"><label className="form-field">Nova tag<input className="text-input" name="name" pattern="[a-z0-9-]+" placeholder="ex.: integration" required/></label><button type="submit" className="button-primary">Adicionar</button></form></section>}
    {section === "macros" && <section className="panel form-panel"><h2>Respostas rápidas</h2><p className="muted">Use / no editor de tickets para inserir uma resposta.</p>{macros.map((macro) => <div className="macro-settings-row" key={macro.id}><strong>/{macro.command}</strong><span>{macro.body}</span></div>)}<form action={createMacroAction} className="macro-form"><div className="eyebrow">CRIAR MACRO</div><label className="form-field">Comando<input className="text-input" name="command" placeholder="request-info" pattern="[a-z0-9-]+" required/></label><label className="form-field">Título<input className="text-input" name="title" placeholder="Solicitar informações" required/></label><label className="form-field">Texto<textarea className="text-input" name="body" rows={4} minLength={5} required/></label><button type="submit" className="button-primary">Salvar resposta</button></form></section>}
    {section === "security" && <section className="panel form-panel"><h2>Segurança e sessão</h2><p className="muted">Contas reais com confirmação de e-mail, sessões JWT e controle de papéis. O servidor fica restrito a localhost.</p><div className="notice">Para uma implantação pública, serão necessários HTTPS, infraestrutura de e-mail e auditoria de segurança adicional.</div><form action={logout} style={{ marginTop: 20 }}><button type="submit" className="button-secondary">Sair da conta</button></form></section>}
    {section === "privacy" && <section className="panel"><div className="section-head"><h2>Pedidos de privacidade</h2><span className="muted">{privacyRequests.filter((item) => item.status === "pending").length} pendentes</span></div><div className="notice" style={{ margin: 18 }}>Analise os pedidos com o responsável pelos dados. A solicitação não exclui registros automaticamente; documente a decisão, o prazo de retenção e a resposta ao titular.</div>{privacyRequests.map((item) => <div className="privacy-request-row" key={item.id}><div><strong>{item.name}</strong><small>{item.email}</small></div><span>{item.request_kind === "deletion" ? "Eliminação" : item.request_kind}</span><span className="plain-pill">{item.status === "pending" ? "Pendente" : item.status}</span><time>{new Date(item.created_at).toLocaleString("pt-BR")}</time></div>)}{privacyRequests.length === 0 && <div className="empty-state">Nenhum pedido recebido.</div>}</section>}
    {section === "audit" && <section className="panel"><div className="section-head"><h2>Registro de auditoria</h2></div>{audit.length ? audit.map((entry) => <div className="audit-row" key={entry.id}><div><strong>{entry.action.replaceAll("_", " ")}</strong><small>{entry.entity_type} · {entry.actor_id}</small></div><span className="muted">{entry.old_value ?? "—"} → {entry.new_value ?? "—"}</span><time className="muted">{new Date(entry.created_at).toLocaleString("pt-BR")}</time></div>) : <div className="empty-state">As ações realizadas aparecerão aqui.</div>}</section>}
  </div></div></>;
}
