"use client";

import { useState } from "react";
import type { Agent } from "@/lib/local/types";
import { createAutomationAction } from "@/features/automations/actions";

export function AutomationBuilder({ agents }: { agents: Agent[] }) {
  const [field, setField] = useState("priority");
  const [action, setAction] = useState("assign");
  return <form action={createAutomationAction} className="automation-builder panel"><div className="eyebrow">NOVA REGRA</div><label className="form-field">Nome<input name="name" className="text-input" placeholder="Ex.: Encaminhar urgências" minLength={4} maxLength={100} required/></label><div className="rule-row"><strong>WHEN</strong><select name="trigger" className="text-input" defaultValue="ticket_created"><option value="ticket_created">Ticket criado</option><option value="status_changed">Status alterado</option></select></div><div className="rule-row"><strong>IF</strong><select name="field" className="text-input" value={field} onChange={(event) => setField(event.target.value)}><option value="priority">Prioridade</option><option value="status">Status</option><option value="subject_contains">Assunto contém</option></select>{field === "priority" ? <select name="value" className="text-input"><option value="urgent">Urgente</option><option value="high">Alta</option><option value="medium">Média</option><option value="low">Baixa</option></select> : field === "status" ? <select name="value" className="text-input"><option value="open">Aberto</option><option value="in_progress">Em andamento</option><option value="waiting_customer">Aguardando cliente</option><option value="resolved">Resolvido</option></select> : <input name="value" className="text-input" placeholder="Ex.: invoice" required/>}</div><div className="rule-row"><strong>THEN</strong><select name="action" className="text-input" value={action} onChange={(event) => setAction(event.target.value)}><option value="assign">Atribuir agente</option><option value="priority">Alterar prioridade</option><option value="tag">Adicionar tag</option><option value="notify">Notificar agente</option></select>{action === "assign" || action === "notify" ? <select name="actionValue" className="text-input">{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select> : action === "priority" ? <select name="actionValue" className="text-input"><option value="urgent">Urgente</option><option value="high">Alta</option><option value="medium">Média</option><option value="low">Baixa</option></select> : <input name="actionValue" className="text-input" placeholder="Ex.: billing" required pattern="[a-z0-9-]+"/>}</div><div className="form-actions"><button type="submit" className="button-primary">Criar automação</button></div></form>;
}
