import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Aviso de privacidade" };
export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  const contact = process.env.PRIVACY_CONTACT_EMAIL;
  const controller = process.env.PRIVACY_CONTROLLER_NAME;
  return <main className="privacy-page"><Link href="/" className="back-link">← Início</Link><div className="eyebrow">PRIVACIDADE · VERSÃO 25/09/2026</div><h1>Aviso de privacidade</h1><p>O NexaDesk é uma aplicação de atendimento executada apenas no computador onde foi instalada. {controller ? <>Responsável pelos dados: <strong>{controller}</strong>.</> : "O responsável pelo workspace deve informar sua identidade aos clientes."}</p><h2>Dados e finalidades</h2><p>Tratamos nome, e-mail, senha protegida por hash, papel de acesso, solicitações, mensagens, anexos e registros de auditoria para criar contas, confirmar e-mails, prestar suporte, proteger o serviço e atender pedidos dos titulares. O provedor SMTP configurado recebe o e-mail de destino e o conteúdo das mensagens de confirmação e recuperação. Não há rastreadores de publicidade nem envio de tickets a um serviço de IA externo.</p><h2>Acesso e armazenamento</h2><p>Os registros ficam no banco PostgreSQL local quando configurado, ou no SQLite local antes da migração; os anexos ficam em arquivos locais. Somente usuários autenticados do workspace acessam os dados permitidos por seu papel. Clientes veem apenas suas solicitações e respostas públicas. O cookie de sessão é necessário para autenticação, tem duração limitada e não é usado para publicidade.</p><h2>Seus direitos</h2><p>Na área <Link href="/account">Minha conta</Link>, você pode corrigir o nome, exportar dados vinculados à conta e solicitar eliminação. Pedidos adicionais de acesso, correção, oposição ou informações sobre compartilhamento podem ser dirigidos ao responsável pelo workspace{contact ? <> em <a href={`mailto:${contact}`}>{contact}</a></> : "."} A eliminação depende da análise de obrigações legais e da necessidade de manter registros de atendimento.</p><h2>Proteção e retenção</h2><p>O servidor escuta somente em localhost, senhas são armazenadas com scrypt, links de confirmação expiram e sessões podem ser revogadas. O responsável pelo workspace deve proteger o computador, os backups e as credenciais SMTP, definir prazos de retenção e avaliar incidentes conforme a LGPD. Esta implementação local não substitui a avaliação jurídica e operacional do tratamento realizado por cada organização.</p></main>;
}
