create extension if not exists pgcrypto;

create type public.member_role as enum ('owner', 'admin', 'supervisor', 'agent', 'customer');
create type public.ticket_status as enum ('open', 'in_progress', 'waiting_customer', 'resolved', 'closed');
create type public.ticket_priority as enum ('low', 'medium', 'high', 'urgent');
create type public.ticket_channel as enum ('portal', 'web', 'email', 'api');
create type public.message_visibility as enum ('public', 'internal');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 2 and 80),
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.member_role not null,
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);
create index organization_members_user_idx on public.organization_members(user_id);

create function public.is_member(org uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.organization_members m where m.organization_id = org and m.user_id = (select auth.uid()));
$$;
create function public.has_role(org uuid, allowed public.member_role[]) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.organization_members m where m.organization_id = org and m.user_id = (select auth.uid()) and m.role = any(allowed));
$$;

create table public.teams (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, created_at timestamptz not null default now(), unique (organization_id, id), unique (organization_id, name)
);
create table public.companies (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, plan text not null default 'Business', account_status text not null default 'active',
  mrr_cents integer not null default 0 check (mrr_cents >= 0), health_score integer check (health_score between 0 and 100),
  created_at timestamptz not null default now(), unique (organization_id, id)
);
create table public.customers (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null, company_id uuid,
  name text not null, email text not null, created_at timestamptz not null default now(),
  unique (organization_id, id), unique (organization_id, email),
  foreign key (organization_id, company_id) references public.companies(organization_id, id)
);
create index customers_user_idx on public.customers(user_id) where user_id is not null;
create function public.owns_customer(org uuid, customer uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.customers c where c.organization_id = org and c.id = customer and c.user_id = (select auth.uid()));
$$;

create table public.sla_policies (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, first_response_minutes integer not null check (first_response_minutes > 0),
  resolution_minutes integer not null check (resolution_minutes > 0), priority public.ticket_priority,
  created_at timestamptz not null default now(), unique (organization_id, id)
);

create table public.tickets (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  number bigint generated by default as identity, subject text not null check (length(trim(subject)) between 3 and 240),
  description text not null default '', status public.ticket_status not null default 'open',
  priority public.ticket_priority not null default 'medium', channel public.ticket_channel not null default 'portal',
  customer_id uuid not null, company_id uuid, assigned_agent_id uuid, assigned_team_id uuid, sla_policy_id uuid,
  sentiment text check (sentiment in ('positive','neutral','negative','frustrated')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  first_response_at timestamptz, resolved_at timestamptz,
  unique (organization_id, id), unique (organization_id, number),
  foreign key (organization_id, customer_id) references public.customers(organization_id, id),
  foreign key (organization_id, company_id) references public.companies(organization_id, id),
  foreign key (organization_id, assigned_agent_id) references public.organization_members(organization_id, user_id),
  foreign key (organization_id, assigned_team_id) references public.teams(organization_id, id),
  foreign key (organization_id, sla_policy_id) references public.sla_policies(organization_id, id)
);
create index tickets_queue_idx on public.tickets(organization_id, status, priority, updated_at desc);
create index tickets_customer_idx on public.tickets(organization_id, customer_id, created_at desc);
create index tickets_assignee_idx on public.tickets(organization_id, assigned_agent_id, status);
create index tickets_search_idx on public.tickets using gin (to_tsvector('english', subject || ' ' || description));

create table public.ticket_messages (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, ticket_id uuid not null,
  author_id uuid references public.profiles(id), visibility public.message_visibility not null default 'public',
  channel public.ticket_channel not null default 'portal', body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now(), unique (organization_id, id),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id) on delete cascade
);
create index ticket_messages_timeline_idx on public.ticket_messages(organization_id, ticket_id, created_at);
create table public.ticket_events (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, ticket_id uuid not null,
  actor_id uuid references public.profiles(id), kind text not null, old_value jsonb, new_value jsonb,
  created_at timestamptz not null default now(),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id) on delete cascade
);
create index ticket_events_timeline_idx on public.ticket_events(organization_id, ticket_id, created_at);
create table public.tags (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, unique (organization_id, id), unique (organization_id, name)
);
create table public.ticket_tags (
  organization_id uuid not null, ticket_id uuid not null, tag_id uuid not null,
  primary key (organization_id, ticket_id, tag_id),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id) on delete cascade,
  foreign key (organization_id, tag_id) references public.tags(organization_id, id) on delete cascade
);
create table public.ticket_assignees (
  organization_id uuid not null, ticket_id uuid not null, user_id uuid not null,
  assigned_at timestamptz not null default now(), primary key (organization_id, ticket_id, user_id),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id) on delete cascade,
  foreign key (organization_id, user_id) references public.organization_members(organization_id, user_id)
);
create table public.sla_events (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, ticket_id uuid not null,
  kind text not null, due_at timestamptz not null, occurred_at timestamptz,
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id) on delete cascade
);
create index sla_events_due_idx on public.sla_events(organization_id, due_at) where occurred_at is null;
create table public.automations (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, enabled boolean not null default false, trigger_kind text not null,
  conditions jsonb not null default '[]', actions jsonb not null default '[]',
  created_at timestamptz not null default now(), unique (organization_id, id)
);
create table public.automation_runs (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, automation_id uuid not null,
  ticket_id uuid not null, result text not null, details jsonb not null default '{}', created_at timestamptz not null default now(),
  foreign key (organization_id, automation_id) references public.automations(organization_id, id),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id)
);
create table public.canned_responses (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  command text not null, title text not null, body text not null, actions jsonb not null default '[]',
  unique (organization_id, command)
);
create table public.knowledge_categories (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, slug text not null, unique (organization_id, id), unique (organization_id, slug)
);
create table public.knowledge_articles (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  category_id uuid, author_id uuid references public.profiles(id), title text not null, slug text not null,
  body text not null default '', status text not null default 'draft' check (status in ('draft','published')),
  reading_minutes integer not null default 1, views integer not null default 0, helpful_votes integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (organization_id, id), unique (organization_id, slug),
  foreign key (organization_id, category_id) references public.knowledge_categories(organization_id, id)
);
create index knowledge_search_idx on public.knowledge_articles using gin (to_tsvector('english', title || ' ' || body));
create table public.notifications (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null,
  recipient_id uuid not null, kind text not null, payload jsonb not null default '{}', read_at timestamptz,
  created_at timestamptz not null default now(),
  foreign key (organization_id, recipient_id) references public.organization_members(organization_id, user_id)
);
create index notifications_unread_idx on public.notifications(organization_id, recipient_id, created_at desc) where read_at is null;
create table public.attachments (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, message_id uuid not null,
  storage_path text not null, file_name text not null, mime_type text not null, size_bytes integer not null check (size_bytes between 1 and 10485760),
  foreign key (organization_id, message_id) references public.ticket_messages(organization_id, id) on delete cascade
);
create table public.customer_feedback (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, ticket_id uuid not null,
  customer_id uuid not null, rating integer not null check (rating between 1 and 5), comment text, created_at timestamptz not null default now(),
  unique (organization_id, ticket_id),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id),
  foreign key (organization_id, customer_id) references public.customers(organization_id, id)
);
create table public.ai_suggestions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null, ticket_id uuid not null,
  requested_by uuid not null references public.profiles(id), kind text not null, content jsonb not null,
  accepted_at timestamptz, created_at timestamptz not null default now(),
  foreign key (organization_id, ticket_id) references public.tickets(organization_id, id)
);
create table public.audit_logs (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_id uuid references public.profiles(id), entity_type text not null, entity_id uuid, action text not null,
  old_value jsonb, new_value jsonb, created_at timestamptz not null default now()
);
create index audit_logs_org_time_idx on public.audit_logs(organization_id, created_at desc);

create function public.touch_ticket() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
create trigger tickets_touch before update on public.tickets for each row execute function public.touch_ticket();

create function public.create_profile() returns trigger language plpgsql security definer set search_path = '' as $$
begin insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', '')); return new; end; $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.create_profile();

create function public.create_organization(workspace_name text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare result uuid; clean_name text; user_id uuid;
begin
  user_id := auth.uid();
  if user_id is null then raise exception 'Authentication required'; end if;
  clean_name := trim(workspace_name);
  if length(clean_name) < 2 or length(clean_name) > 80 then raise exception 'Invalid workspace name'; end if;
  insert into public.organizations(name, slug) values (clean_name, lower(regexp_replace(clean_name, '[^a-zA-Z0-9]+', '-', 'g')) || '-' || substr(gen_random_uuid()::text, 1, 8)) returning id into result;
  insert into public.organization_members(organization_id, user_id, role) values (result, user_id, 'owner');
  return result;
end; $$;
revoke all on function public.create_organization(text) from public;
grant execute on function public.create_organization(text) to authenticated;

create function public.guard_member_roles() returns trigger
language plpgsql security definer set search_path = '' as $$
declare org uuid; owner_count integer;
begin
  org := case when tg_op = 'DELETE' then old.organization_id else new.organization_id end;
  if tg_op = 'INSERT' then
    if new.role in ('owner', 'admin') and public.is_member(org) and not public.has_role(org, array['owner']::public.member_role[]) then
      raise exception 'Only an owner can grant elevated roles';
    end if;
    return new;
  end if;
  if tg_op = 'UPDATE' and (new.organization_id <> old.organization_id or new.user_id <> old.user_id) then
    raise exception 'Membership identity cannot be changed';
  end if;
  if old.role = 'owner' then
    select count(*) into owner_count from public.organization_members where organization_id = org and role = 'owner';
    if owner_count <= 1 and (tg_op = 'DELETE' or new.role <> 'owner') then
      raise exception 'An organization must retain an owner';
    end if;
  end if;
  if tg_op = 'UPDATE' and (new.role in ('owner', 'admin') or old.role in ('owner', 'admin')) and not public.has_role(org, array['owner']::public.member_role[]) then
    raise exception 'Only an owner can change elevated roles';
  end if;
  if tg_op = 'DELETE' and old.role in ('owner', 'admin') and not public.has_role(org, array['owner']::public.member_role[]) then
    raise exception 'Only an owner can remove elevated roles';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end; $$;
create trigger member_role_guard before insert or update or delete on public.organization_members
for each row execute function public.guard_member_roles();

alter table public.profiles enable row level security;
create policy profiles_read on public.profiles for select to authenticated using (id = (select auth.uid()) or exists (select 1 from public.organization_members m where m.user_id = profiles.id and public.has_role(m.organization_id, array['owner','admin','supervisor','agent']::public.member_role[])));
create policy profiles_update on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
alter table public.organizations enable row level security;
create policy organizations_read on public.organizations for select to authenticated using (public.is_member(id));
create policy organizations_update on public.organizations for update to authenticated using (public.has_role(id, array['owner','admin']::public.member_role[])) with check (public.has_role(id, array['owner','admin']::public.member_role[]));
alter table public.organization_members enable row level security;
create policy members_read on public.organization_members for select to authenticated using (user_id = (select auth.uid()) or public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy members_manage on public.organization_members for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));

alter table public.teams enable row level security;
create policy teams_read on public.teams for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy teams_manage on public.teams for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.companies enable row level security;
create policy companies_read on public.companies for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy companies_manage on public.companies for all to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor']::public.member_role[]));
alter table public.customers enable row level security;
create policy customers_read on public.customers for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or user_id = (select auth.uid()));
create policy customers_manage on public.customers for all to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.sla_policies enable row level security;
create policy sla_read on public.sla_policies for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy sla_manage on public.sla_policies for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.tickets enable row level security;
create policy tickets_read on public.tickets for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or public.owns_customer(organization_id, customer_id));
create policy tickets_create on public.tickets for insert to authenticated with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or (public.owns_customer(organization_id, customer_id) and assigned_agent_id is null and assigned_team_id is null and status = 'open'));
create policy tickets_update on public.tickets for update to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.ticket_messages enable row level security;
create policy messages_read on public.ticket_messages for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or (visibility = 'public' and exists (select 1 from public.tickets t where t.organization_id = ticket_messages.organization_id and t.id = ticket_messages.ticket_id and public.owns_customer(t.organization_id, t.customer_id))));
create policy messages_create on public.ticket_messages for insert to authenticated with check (author_id = (select auth.uid()) and (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or (visibility = 'public' and exists (select 1 from public.tickets t where t.organization_id = ticket_messages.organization_id and t.id = ticket_messages.ticket_id and public.owns_customer(t.organization_id, t.customer_id)))));
alter table public.ticket_events enable row level security;
create policy events_read on public.ticket_events for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.tags enable row level security;
create policy tags_read on public.tags for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy tags_manage on public.tags for all to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.ticket_tags enable row level security;
create policy ticket_tags_staff on public.ticket_tags for all to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.ticket_assignees enable row level security;
create policy assignees_staff on public.ticket_assignees for all to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.sla_events enable row level security;
create policy sla_events_staff on public.sla_events for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.automations enable row level security;
create policy automations_read on public.automations for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor']::public.member_role[]));
create policy automations_manage on public.automations for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.automation_runs enable row level security;
create policy automation_runs_read on public.automation_runs for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor']::public.member_role[]));
alter table public.canned_responses enable row level security;
create policy macros_read on public.canned_responses for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy macros_manage on public.canned_responses for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.knowledge_categories enable row level security;
create policy categories_read on public.knowledge_categories for select to authenticated using (public.is_member(organization_id));
create policy categories_manage on public.knowledge_categories for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.knowledge_articles enable row level security;
create policy articles_read on public.knowledge_articles for select to authenticated using ((status = 'published' and public.is_member(organization_id)) or public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
create policy articles_manage on public.knowledge_articles for all to authenticated using (public.has_role(organization_id, array['owner','admin']::public.member_role[])) with check (public.has_role(organization_id, array['owner','admin']::public.member_role[]));
alter table public.notifications enable row level security;
create policy notifications_read on public.notifications for select to authenticated using (recipient_id = (select auth.uid()));
create policy notifications_update on public.notifications for update to authenticated using (recipient_id = (select auth.uid())) with check (recipient_id = (select auth.uid()));
alter table public.attachments enable row level security;
create policy attachments_read on public.attachments for select to authenticated using (exists (select 1 from public.ticket_messages m where m.organization_id = attachments.organization_id and m.id = attachments.message_id));
alter table public.customer_feedback enable row level security;
create policy feedback_read on public.customer_feedback for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]) or public.owns_customer(organization_id, customer_id));
create policy feedback_create on public.customer_feedback for insert to authenticated with check (public.owns_customer(organization_id, customer_id));
alter table public.ai_suggestions enable row level security;
create policy ai_staff on public.ai_suggestions for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor','agent']::public.member_role[]));
alter table public.audit_logs enable row level security;
create policy audit_read on public.audit_logs for select to authenticated using (public.has_role(organization_id, array['owner','admin','supervisor']::public.member_role[]));

alter publication supabase_realtime add table public.tickets, public.ticket_messages, public.notifications;
